services:
  backend:
    build: './backend'
    env_file: './backend/.env'
    volumes:
      - ./backend:/app
    ports:
      - '8001:8000'

  frontend:
    build: './frontend'
    ports:
      - '3001:3000'
    depends_on:
      - backend

  reverse-proxy:
    image: nginx:stable-alpine
    ports:
      - '8082:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
